language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo "before_install"
  - sudo apt-get update -qq
  - sudo apt-get install -qq sudo

# Install any prerequisites or dependencies for the build.
install:
  - echo "install"

# Prepare build for testing, e.g. env variables, database config.
before_script:
  - echo "before_script"

# Commands must end with 0 to show success.
script:
  - echo "script"
  - make

after_success:
  - echo "after_success"

after_failure:
  - echo "after_failure"

after_script:
  - echo "after_script"
  - echo $TRAVIS_TEST_RESULT
